#!/usr/bin/env python3

from dextrous_hand.ids import *
from dextrous_hand.FingerJoints import PIP, DIP, MCP, ABD
from dextrous_hand.WristJoint import WristJoint

SUBSYSTEM_MOTORS = {
    SUBSYSTEMS.PINKY :  [MOTORS.PINKY_UMBM,
                         MOTORS.PINKY_URBL,
                         MOTORS.PINKY_ULBR],

    SUBSYSTEMS.RING :   [MOTORS.RING_UMBM,
                         MOTORS.RING_URBL,
                         MOTORS.RING_ULBR],

    SUBSYSTEMS.MIDDLE : [MOTORS.MIDDLE_UMBM,
                         MOTORS.MIDDLE_URBL,
                         MOTORS.MIDDLE_ULBR],

    SUBSYSTEMS.INDEX :  [MOTORS.INDEX_UMBM,
                         MOTORS.INDEX_URBL,
                         MOTORS.INDEX_ULBR],

    SUBSYSTEMS.THUMB :  [MOTORS.THUMB_UMBM,
                         MOTORS.THUMB_URBL,
                         MOTORS.THUMB_ULBR],

    SUBSYSTEMS.WRIST :  [MOTORS.WRIST]
}
"""
Motors for each subsystem
"""

JOINT_MOTORS = {
    JOINTS.PINKY_ABD: [MOTORS.PINKY_URBL, MOTORS.PINKY_ULBR],
    JOINTS.PINKY_MCP: [MOTORS.PINKY_URBL, MOTORS.PINKY_ULBR],
    JOINTS.PINKY_PIP: [MOTORS.PINKY_UMBM],
    JOINTS.PINKY_DIP: [MOTORS.PINKY_UMBM],

    JOINTS.RING_ABD: [MOTORS.RING_URBL, MOTORS.RING_ULBR],
    JOINTS.RING_MCP: [MOTORS.RING_URBL, MOTORS.RING_ULBR],
    JOINTS.RING_PIP: [MOTORS.RING_UMBM],
    JOINTS.RING_DIP: [MOTORS.RING_UMBM],

    JOINTS.MIDDLE_ABD: [MOTORS.MIDDLE_URBL, MOTORS.MIDDLE_ULBR],
    JOINTS.MIDDLE_MCP: [MOTORS.MIDDLE_URBL, MOTORS.MIDDLE_ULBR],
    JOINTS.MIDDLE_PIP: [MOTORS.MIDDLE_UMBM],
    JOINTS.MIDDLE_DIP: [MOTORS.MIDDLE_UMBM],

    JOINTS.INDEX_ABD: [MOTORS.INDEX_URBL, MOTORS.INDEX_ULBR],
    JOINTS.INDEX_MCP: [MOTORS.INDEX_URBL, MOTORS.INDEX_ULBR],
    JOINTS.INDEX_PIP: [MOTORS.INDEX_UMBM],
    JOINTS.INDEX_DIP: [MOTORS.INDEX_UMBM],

    JOINTS.THUMB_ABD: [MOTORS.THUMB_URBL, MOTORS.THUMB_ULBR],
    JOINTS.THUMB_MCP: [MOTORS.THUMB_URBL, MOTORS.THUMB_ULBR],
    JOINTS.THUMB_PIP: [MOTORS.THUMB_UMBM],
    JOINTS.THUMB_DIP: [MOTORS.THUMB_UMBM],

    JOINTS.WRIST: [MOTORS.WRIST]}
"""
Motor composition for each joint
"""

SUBSYSTEM_JOINTS = {
    SUBSYSTEMS.PINKY: [ABD(JOINTS.PINKY_ABD),
                       MCP(JOINTS.PINKY_MCP),
                       PIP(JOINTS.PINKY_PIP),
                       DIP(JOINTS.PINKY_DIP)],

    SUBSYSTEMS.RING: [ABD(JOINTS.RING_ABD),
                      MCP(JOINTS.RING_MCP),
                      PIP(JOINTS.RING_PIP),
                      DIP(JOINTS.RING_DIP)],

    SUBSYSTEMS.MIDDLE: [ABD(JOINTS.MIDDLE_ABD),
                        MCP(JOINTS.MIDDLE_MCP),
                        PIP(JOINTS.MIDDLE_PIP),
                        DIP(JOINTS.MIDDLE_DIP)],

    SUBSYSTEMS.INDEX: [ABD(JOINTS.INDEX_ABD),
                       MCP(JOINTS.INDEX_MCP),
                       PIP(JOINTS.INDEX_PIP),
                       DIP(JOINTS.INDEX_DIP)],

    SUBSYSTEMS.THUMB: [ABD(JOINTS.THUMB_ABD),
                       MCP(JOINTS.THUMB_MCP),
                       PIP(JOINTS.THUMB_PIP),
                       DIP(JOINTS.THUMB_DIP)],

    SUBSYSTEMS.WRIST: [WristJoint(JOINTS.WRIST)]
}
"""
Joints for each subsystem
"""