#!/usr/bin/env python3

from numpy import pi as PI
from dextrous_hand.ids import MOTORS, STARTUP, MOTOR_DIRECTION
from dextrous_hand.HandConfig import HandConfig
import dextrous_hand.configs as configs

IS_SIMULATION = False # Set to True if the motor controller is not connected

MANUAL_CONTROL = False # Set to True to disable the hand and control the motors manually but still be able to read the sensors

DEVICE_NAME = "/dev/ttyUSB0" # Change this if the motor controller is connected to a different port
BAUDRATE = 3000000

NODE_FREQUENCY_HZ = 1000

STARTUP_MODE = STARTUP.LAST
"""
Defines the startup mode for the hand. Options are:
- HOME: The hand will start in the home configuration.
- LAST: The hand will start in the last configuration it was in.
- CUSTOM: The hand will start in the configuration defined by the INITIAL_CONFIG variable.
"""

INITIAL_CONFIG = configs.HOME

"""
Custom starting configuration
"""

FULL_RANGE = [-1.0, 2*PI]
MOTOR_LIMITS = {
    MOTORS.THUMB_FLBR: FULL_RANGE,
    MOTORS.THUMB_FRBL: FULL_RANGE,
    MOTORS.THUMB_FMBM: FULL_RANGE,

    MOTORS.INDEX_FLBR: FULL_RANGE,
    MOTORS.INDEX_FRBL: FULL_RANGE,
    MOTORS.INDEX_FMBM: FULL_RANGE,

    MOTORS.MIDDLE_FLBR: FULL_RANGE,
    MOTORS.MIDDLE_FRBL: FULL_RANGE,
    MOTORS.MIDDLE_FMBM: FULL_RANGE,

    MOTORS.RING_FLBR: FULL_RANGE,
    MOTORS.RING_FRBL: FULL_RANGE,
    MOTORS.RING_FMBM: FULL_RANGE,

    MOTORS.PINKY_FLBR: FULL_RANGE,
    MOTORS.PINKY_FRBL: FULL_RANGE,
    MOTORS.PINKY_FMBM: FULL_RANGE,

    MOTORS.WRIST: FULL_RANGE
}
"""
Hard limits for the motors to prevent overextension.
"""

MOTOR_ZEROS = {
    MOTORS.THUMB_FLBR: 0,
    MOTORS.THUMB_FRBL: 0,
    MOTORS.THUMB_FMBM: 0,

    MOTORS.INDEX_FLBR: 3.40,
    MOTORS.INDEX_FRBL: 3.00,
    MOTORS.INDEX_FMBM: 3.35,

    MOTORS.MIDDLE_FLBR: 2.69,
    MOTORS.MIDDLE_FRBL: 3.94,
    MOTORS.MIDDLE_FMBM: 3.31,

    MOTORS.RING_FLBR: 2.00,
    MOTORS.RING_FRBL: 3.75,
    MOTORS.RING_FMBM: 3.72,

    MOTORS.PINKY_FLBR: 3.61,
    MOTORS.PINKY_FRBL: 3.58,
    MOTORS.PINKY_FMBM: 1.97,

    MOTORS.WRIST: 0
}
"""
Offset to zero the motors.
"""

MOTOR_DIRECTIONS = {
    MOTORS.THUMB_FLBR: MOTOR_DIRECTION.FORWARD,
    MOTORS.THUMB_FRBL: MOTOR_DIRECTION.FORWARD,
    MOTORS.THUMB_FMBM: MOTOR_DIRECTION.FORWARD,

    MOTORS.INDEX_FLBR: MOTOR_DIRECTION.REVERSED,
    MOTORS.INDEX_FRBL: MOTOR_DIRECTION.FORWARD,
    MOTORS.INDEX_FMBM: MOTOR_DIRECTION.REVERSED,

    MOTORS.MIDDLE_FLBR: MOTOR_DIRECTION.FORWARD,
    MOTORS.MIDDLE_FRBL: MOTOR_DIRECTION.REVERSED,
    MOTORS.MIDDLE_FMBM: MOTOR_DIRECTION.REVERSED,

    MOTORS.RING_FLBR: MOTOR_DIRECTION.FORWARD,
    MOTORS.RING_FRBL: MOTOR_DIRECTION.REVERSED,
    MOTORS.RING_FMBM: MOTOR_DIRECTION.REVERSED,

    MOTORS.PINKY_FLBR: MOTOR_DIRECTION.FORWARD,
    MOTORS.PINKY_FRBL: MOTOR_DIRECTION.REVERSED,
    MOTORS.PINKY_FMBM: MOTOR_DIRECTION.FORWARD,

    MOTORS.WRIST: MOTOR_DIRECTION.FORWARD
}
"""
Direction of the motors.
"""